profiles: 
  prod:
    username: max
    password: pas
    url: jdbc:postgresql://db:5432/university
    driver: org.postgresql.Driver
  test:
    username: max
    password: pas
    url: jdbc:postgresql://test_db:5432/university
    driver: org.h2.Driver
  local:
    username: max
    password: pas
    url: jdbc:postgresql://localhost:5432/university
    driver: org.h2.Driver
