profiles: 
  prod:
    username: max
    password: pas
    url: jdbc:postgresql://db:5432/university
    driver: org.postgresql.Driver
  test:
    username: max
    password: pas
    url: jdbc:h2:~/university;INIT=RUNSCRIPT FROM 'classpath:scripts/init_script.sql';DB_CLOSE_DELAY=-1
    driver: org.h2.Driver

